language: android
android:
  components:
    - tools
    - platform-tools
    - android-24
    - build-tools-24.0.3
    - extra

sudo: required

jdk:
  - oraclejdk8

script:
    - java -version
    - ./gradlew assemble
    - ./gradlew test
