language: android
android:
  components:
    - tools
    - platform-tools
    - android-24
    - build-tools-24.0.3
    - extra

sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer

script:
    - ./gradlew assemble
    - ./gradlew test
